package com.steleot.blekotlin.internal.utils

import com.steleot.blekotlin.BleAdapter
import com.steleot.blekotlin.BleDevice
import com.steleot.blekotlin.BleGatt
import com.steleot.blekotlin.BleScanCallback
import com.steleot.blekotlin.constants.BleGattCharacteristicUuids
import com.steleot.blekotlin.constants.BleGattDescriptorUuids
import com.steleot.blekotlin.constants.BleGattServiceUuids

/**
 * The bluetooth statuses for logging purposes.
 */
internal val bleStatuses by lazy {
    mapOf(
        BleAdapter.STATE_OFF to "Bluetooth state off",
        BleAdapter.STATE_TURNING_ON to "Bluetooth state turning on",
        BleAdapter.STATE_ON to "Bluetooth state on",
        BleAdapter.STATE_TURNING_OFF to "Bluetooth state turning off",
    )
}

/**
 * The bluetooth device bond states for logging purposes.
 */
internal val bleBondStates by lazy {
    mapOf(
        BleDevice.BOND_NONE to "Bond none",
        BleDevice.BOND_BONDING to "Bond bonding",
        BleDevice.BOND_BONDED to "Bond bonded",
    )
}

/**
 * The bluetooth scan callback statuses for logging purposes.
 */
internal val scanCallbackStatuses by lazy {
    mapOf(
        BleScanCallback.SCAN_FAILED_ALREADY_STARTED
                to "Ble scan failed - Already started",
        BleScanCallback.SCAN_FAILED_APPLICATION_REGISTRATION_FAILED
                to "Ble scan failed - Application registration failed",
        BleScanCallback.SCAN_FAILED_INTERNAL_ERROR
                to "Ble scan failed - Internal server error",
        BleScanCallback.SCAN_FAILED_FEATURE_UNSUPPORTED
                to "Ble scan failed - Feature unsupported",
        5 to "Ble scan failed - out of hardware resources",
        6 to "Ble scan failed - scanning too frequently",
    )
}

/**
 * The bluetooth gatt statuses for logging purposes.
 */
internal val gattStatuses by lazy {
    mapOf(
        BleGatt.GATT_SUCCESS to "Gatt success",
        0x01 to "Gatt invalid handle",
        BleGatt.GATT_READ_NOT_PERMITTED to "Gatt read not permitted",
        BleGatt.GATT_WRITE_NOT_PERMITTED to "Gatt write not permitted",
        0x04 to "Gatt invalid pdu",
        BleGatt.GATT_INSUFFICIENT_AUTHENTICATION to "Gatt insufficient authentication",
        BleGatt.GATT_REQUEST_NOT_SUPPORTED to "Gatt request not supported",
        BleGatt.GATT_INVALID_OFFSET to "Gatt invalid offset",
        0x08 to "Gatt insufficient authorization or connection timeout",
        0x09 to "Gatt prepare q full",
        0x0a to "Gatt not found",
        0x0b to "Gatt not long",
        0x0c to "Gatt insufficient key size",
        BleGatt.GATT_INVALID_ATTRIBUTE_LENGTH to "Gatt invalid attribute length",
        0x0e to "Gatt error unlikely",
        BleGatt.GATT_INSUFFICIENT_ENCRYPTION to "Gatt insufficient encryption",
        0x10 to "Gatt unsupported grp type",
        0x11 to "Gatt insufficient resource",
        0x13 to "Gatt connection terminate peer user",
        0x16 to "Gatt connection terminate local host",
        0x22 to "Gatt connection lmp timeout",
        0x3e to "Gatt connection fail establish",
        0x87 to "GATT_ILLEGAL_PARAMETER",
        0x80 to "Gatt no resources",
        0x81 to "Gatt internal error",
        0x82 to "Gatt wrong state",
        0x83 to "Gatt db full",
        0x84 to "Gatt busy",
        0x85 to "Gatt error",
        0x86 to "Gatt cmd started",
        0x88 to "Gatt pending",
        0x89 to "Gatt auth fail",
        0x8a to "Gatt more",
        0x8b to "Gatt invalid cfg",
        0x8c to "Gatt service started",
        0x8d to "Gatt encrypted no mitm",
        0x8e to "Gatt not encrypted",
        BleGatt.GATT_CONNECTION_CONGESTED to "Gatt connection congested",
        0xfd to "Gatt ccc cfg err",
        0xfe to "Gatt prc in progress",
        0xff to "Gatt out of range",
        0x100 to "Gatt connection cancel",
        BleGatt.GATT_FAILURE to "Gatt failure"
    )
}

/**
 * The bluetooth gatt service uuids for logging purposes.
 */
internal val gattServicesUuids by lazy {
    mapOf(
        BleGattServiceUuids.GENERIC_ACCESS to "Generic Access",
        BleGattServiceUuids.GENERIC_ATTRIBUTE to "Generic Attribute",
        BleGattServiceUuids.IMMEDIATE_ALERT to "Immediate Alert",
        BleGattServiceUuids.LINK_LOSS to "Link Loss",
        BleGattServiceUuids.TX_POWER to "Tx Power",
        BleGattServiceUuids.CURRENT_TIME_SERVICE to "Current Time Service",
        BleGattServiceUuids.REFERENCE_TIME_UPDATE_SERVICE to "Reference Time Update Service",
        BleGattServiceUuids.NEXT_DST_CHANGE_SERVICE to "Next DST Change Service",
        BleGattServiceUuids.GLUCOSE to "Glucose",
        BleGattServiceUuids.HEALTH_THERMOMETER to "Health Thermometer",
        BleGattServiceUuids.DEVICE_INFORMATION to "Device Information",
        BleGattServiceUuids.HEART_RATE to "Heart Rate",
        BleGattServiceUuids.PHONE_ALERT_STATUS_SERVICE to "Phone Alert Status Service",
        BleGattServiceUuids.BATTERY_SERVICE to "Battery Service",
        BleGattServiceUuids.BLOOD_PRESSURE to "Blood Pressure",
        BleGattServiceUuids.ALERT_NOTIFICATION_SERVICE to "Alert Notification Service",
        BleGattServiceUuids.HUMAN_INTERFACE_DEVICE to "Human Interface Device",
        BleGattServiceUuids.SCAN_PARAMETERS to "Scan Parameters",
        BleGattServiceUuids.RUNNING_SPEED_AND_CADENCE to "Running Speed and Cadence",
        BleGattServiceUuids.AUTOMATION_IO to "Automation IO",
        BleGattServiceUuids.CYCLING_SPEED_AND_CADENCE to "Cycling Speed and Cadence",
        BleGattServiceUuids.CYCLING_POWER to "Cycling Power",
        BleGattServiceUuids.LOCATION_AND_NAVIGATION to "Location and Navigation",
        BleGattServiceUuids.ENVIRONMENTAL_SENSING to "Environmental Sensing",
        BleGattServiceUuids.BODY_COMPOSITION to "Body Composition",
        BleGattServiceUuids.USER_DATA to "User Data",
        BleGattServiceUuids.WEIGHT_SCALE to "Weight Scale",
        BleGattServiceUuids.BOND_MANAGEMENT to "Bond Management",
        BleGattServiceUuids.CONTINUOUS_GLUCOSE_MONITORING to "Continuous Glucose Monitoring",
        BleGattServiceUuids.INTERNET_PROTOCOL_SUPPORT to "Internet Protocol Support",
        BleGattServiceUuids.INDOOR_PROTOCOL_SUPPORT to "Indoor Protocol Support",
        BleGattServiceUuids.PULSE_OXIMETER to "Pulse Oximeter",
        BleGattServiceUuids.HTTP_PROXY to "Http Proxy",
        BleGattServiceUuids.TRANSPORT_DISCOVERY to "Transport Discovery",
        BleGattServiceUuids.OBJECT_TRANSFER to "Object Transfer",
        BleGattServiceUuids.FITNESS_MACHINE to "Fitness Machine",
        BleGattServiceUuids.MESH_PROVISIONING to "Mesh Provisioning",
        BleGattServiceUuids.MESH_PROXY to "Mesh Proxy",
        BleGattServiceUuids.RECONNECTION_CONFIGURATION to "Reconnection Configuration",
        BleGattServiceUuids.INSULIN_DELIVERY to "Insulin Delivery",
        BleGattServiceUuids.BINARY_SENSOR to "Binary Sensor",
        BleGattServiceUuids.EMERGENCY_CONFIGURATION to "Emergency Configuration",
        BleGattServiceUuids.PHYSICAL_ACTIVITY_MONITOR to "",
        BleGattServiceUuids.AUDIO_INPUT_CONTROL to "Audio Input Control",
        BleGattServiceUuids.VOLUME_CONTROL to "Volume Control",
        BleGattServiceUuids.VOLUME_OFFSET_CONTROL to "Volume Offset Control",
        BleGattServiceUuids.DEVICE_TIME to "Device Time",
    )
}

/**
 * The bluetooth gatt characteristic uuids for logging purposes.
 */
internal val gattCharacteristicUuids by lazy {
    mapOf(
        BleGattCharacteristicUuids.DEVICE_NAME to "Device Name",
        BleGattCharacteristicUuids.APPEARANCE to "Appearance",
        BleGattCharacteristicUuids.PERIPHERAL_PRIVACY_FLAG to "Peripheral Privacy Flag",
        BleGattCharacteristicUuids.RECONNECTION_ADDRESS to "Reconnection Address",
        BleGattCharacteristicUuids.PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS to "Peripheral Preferred Connection Parameters",
        BleGattCharacteristicUuids.SERVICE_CHANGED to "Service Changed",
        BleGattCharacteristicUuids.ALERT_LEVEL to "Alert Level",
        BleGattCharacteristicUuids.TX_POWER_LEVEL to "Tx Power Level",
        BleGattCharacteristicUuids.DATE_TIME to "Date Time",
        BleGattCharacteristicUuids.DAY_OF_WEEK to "Day Of Week",
        BleGattCharacteristicUuids.DAY_DATE_TIME to "Day Date Time",
        BleGattCharacteristicUuids.EXACT_TIME_256 to "Exact Time256",
        BleGattCharacteristicUuids.DST_OFFSET to "Dst Offset",
        BleGattCharacteristicUuids.TIME_ZONE to "Time Zone",
        BleGattCharacteristicUuids.LOCAL_TIME_INFORMATION to "Local Time Information",
        BleGattCharacteristicUuids.TIME_WITH_DST to "Time With Dst",
        BleGattCharacteristicUuids.TIME_ACCURACY to "Time Accuracy",
        BleGattCharacteristicUuids.TIME_SOURCE to "Time Source",
        BleGattCharacteristicUuids.REFERENCE_TIME_INFORMATION to "Reference Time Information",
        BleGattCharacteristicUuids.TIME_UPDATE_CONTROL_POINT to "Time Update Control Point",
        BleGattCharacteristicUuids.TIME_UPDATE_STATE to "Time Update State",
        BleGattCharacteristicUuids.GLUCOSE_MEASUREMENT to "Glucose Measurement",
        BleGattCharacteristicUuids.BATTERY_LEVEL to "Battery Level",
        BleGattCharacteristicUuids.TEMPERATURE_MEASUREMENT to "Temperature Measurement",
        BleGattCharacteristicUuids.TEMPERATURE_TYPE to "Temperature Type",
        BleGattCharacteristicUuids.INTERMEDIATE_TEMPERATURE to "Intermediate Temperature",
        BleGattCharacteristicUuids.MEASUREMENT_INTERVAL to "Measurement Interval",
        BleGattCharacteristicUuids.BOOT_KEYBOARD_INPUT_REPORT to "Boot Keyobard Input Report",
        BleGattCharacteristicUuids.SYSTEM_ID to "System Id",
        BleGattCharacteristicUuids.MODEL_NUMBER_STRING to "Model Number String",
        BleGattCharacteristicUuids.SERIAL_NUMBER_STRING to "Serial Number String",
        BleGattCharacteristicUuids.FIRMWARE_REVISION_STRING to "Firmware Revision String",
        BleGattCharacteristicUuids.HARDWARE_REVISION_STRING to "Hardware Revision String",
        BleGattCharacteristicUuids.SOFTWARE_REVISION_STRING to "Software Revision String",
        BleGattCharacteristicUuids.MANUFACTURER_NAME_STRING to "Manufacturer Name String",
        BleGattCharacteristicUuids.IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST to "Iee 11073 20601 Regulatory Certification Data List",
        BleGattCharacteristicUuids.CURRENT_TIME to "Current Time",
        BleGattCharacteristicUuids.SCAN_REFRESH to "Scan Refresh",
        BleGattCharacteristicUuids.BOOT_KEYBOARD_OUTPUT_REPORT to "Boot Keyboard Ouput Report",
        BleGattCharacteristicUuids.BOOT_MOUSE_INPUT_REPORT to "Boot Mouse Input Report",
        BleGattCharacteristicUuids.GLUCOSE_MEASUREMENT_CONTEXT to "Glucose Measurement Context",
        BleGattCharacteristicUuids.BLOOD_PRESSURE_MEASUREMENT to "Blood Pressure Measurement",
        BleGattCharacteristicUuids.INTERMEDIATE_CUFF_PRESSURE to "Intermediate Cuff Pressure",
        BleGattCharacteristicUuids.HEART_RATE_MEASUREMENT to "Heart Rate Measurement",
        BleGattCharacteristicUuids.BODY_SENSOR_LOCATION to "Body Sensor Location",
        BleGattCharacteristicUuids.HEART_RATE_CONTROL_POINT to "Heart Rate Control Point",
        BleGattCharacteristicUuids.ALERT_STATUS to "Alert Status",
        BleGattCharacteristicUuids.RINGER_CONTROL_POINT to "Ringer Control Point",
        BleGattCharacteristicUuids.RINGER_SETTING to "Ringer Setting",
        BleGattCharacteristicUuids.ALERT_CATEGORY_ID_BIT_MASK to "Alert Category Id Bit Mask",
        BleGattCharacteristicUuids.ALERT_CATEGORY_ID to "Alert Category Id",
        BleGattCharacteristicUuids.ALERT_NOTIFICATION_CONTROL_POINT to "Alert Notification Control Point",
        BleGattCharacteristicUuids.UNREAD_ALERT_STATUS to "Unread Alert Status",
        BleGattCharacteristicUuids.NEW_ALERT to "New Alert",
        BleGattCharacteristicUuids.SUPPORTED_NEW_ALERT_CATEGORY to "Supported New Alert Category",
        BleGattCharacteristicUuids.SUPPORTED_UNREAD_ALERT_CATEGORY to "Supported Unread Alert Category",
        BleGattCharacteristicUuids.BLOOD_PRESSURE_FEATURE to "Blood Pressure Feature",
        BleGattCharacteristicUuids.HID_INFORMATION to "Hid Information",
        BleGattCharacteristicUuids.REPORT_MAP to "Report Map",
        BleGattCharacteristicUuids.HID_CONTROL_POINT to "Hid Control Point",
        BleGattCharacteristicUuids.REPORT to "Report",
        BleGattCharacteristicUuids.PROTOCOL_MODE to "Protocol Mode",
        BleGattCharacteristicUuids.SCAN_INTERVAL_WINDOW to "Scan Interval Window",
        BleGattCharacteristicUuids.PNP_ID to "Pnp Id",
        BleGattCharacteristicUuids.GLUCOSE_FEATURE to "Glucose Feature",
        BleGattCharacteristicUuids.RECORD_ACCESS_CONTROL_POINT to "Record Access Control Point",
        BleGattCharacteristicUuids.RSC_MEASUREMENT to "Rsc Measurement",
        BleGattCharacteristicUuids.RSC_FEATURE to "Rsc Feature",
        BleGattCharacteristicUuids.SC_CONTROL_POINT to "Sc Control Point",
        BleGattCharacteristicUuids.AGGREGATE to "Aggregate",
        BleGattCharacteristicUuids.CSC_MEASUREMENT to "Csc Measurement",
        BleGattCharacteristicUuids.CSC_FEATURE to "Csc Feature",
        BleGattCharacteristicUuids.SENSOR_LOCATION to "Sensor Location",
        BleGattCharacteristicUuids.PLX_SPOT_CHECK_MEASUREMENT to "Plx Spot Check Measurement",
        BleGattCharacteristicUuids.PLX_CONTINUOUS_MEASUREMENT to "Plx Continuous Measurement",
        BleGattCharacteristicUuids.PLX_FEATURES to "Plx Features",
        BleGattCharacteristicUuids.CYCLING_POWER_MEASUREMENT to "Cycling Power Measurement",
        BleGattCharacteristicUuids.CYCLING_POWER_VECTOR to "Cycling Power Vector",
        BleGattCharacteristicUuids.CYCLING_POWER_FEATURE to "Cycling Power Feature",
        BleGattCharacteristicUuids.CYCLING_POWER_CONTROL_POINT to "Cycling Power Control Point",
        BleGattCharacteristicUuids.LOCATION_AND_SPEED to "Location And Speed",
        BleGattCharacteristicUuids.NAVIGATION to "Navigation",
        BleGattCharacteristicUuids.POSITION_QUALITY to "Position Quality",
        BleGattCharacteristicUuids.LN_FEATURE to "Ln Feature",
        BleGattCharacteristicUuids.LN_CONTROL_POINT to "Ln Control Point",
        BleGattCharacteristicUuids.ELEVATION to "Elevation",
        BleGattCharacteristicUuids.PRESSURE to "Pressure",
        BleGattCharacteristicUuids.TEMPERATURE to "Temperature",
        BleGattCharacteristicUuids.HUMIDITY to "Humidity",
        BleGattCharacteristicUuids.TRUE_WIND_SPEED to "True Wind Speed",
        BleGattCharacteristicUuids.TRUE_WIND_DIRECTION to "True Wind Direction",
        BleGattCharacteristicUuids.APPARENT_WIND_SPEED to "Apparent Wind Speed",
        BleGattCharacteristicUuids.APPARENT_WIND_DIRECTION to "Apparent Wind Direction",
        BleGattCharacteristicUuids.GUST_FACTOR to "Gust Factor",
        BleGattCharacteristicUuids.POLLEN_CONCENTRATION to "Pollen Concetration",
        BleGattCharacteristicUuids.UV_INDEX to "Uv Index",
        BleGattCharacteristicUuids.IRRADIANCE to "Irradiance",
        BleGattCharacteristicUuids.RAINFALL to "Rainfall",
        BleGattCharacteristicUuids.WIND_CHILL to "Wind Chill",
        BleGattCharacteristicUuids.HEAT_INDEX to "Heat Index",
        BleGattCharacteristicUuids.DEW_POINT to "Dew Point",
        BleGattCharacteristicUuids.DESCRIPTOR_VALUE_CHANGED to "Descriptor Value Changed",
        BleGattCharacteristicUuids.AEROBIC_HEART_RATE_LOWER_LIMIT to "Aerobic Heart Rate Lower Limit",
        BleGattCharacteristicUuids.AEROBIC_THRESHOLD to "Aerobic Threshold",
        BleGattCharacteristicUuids.AGE to "Age",
        BleGattCharacteristicUuids.ANAEROBIC_HEART_RATE_LOWER_LIMIT to "Anaerobic Heart Rate Lower Limit",
        BleGattCharacteristicUuids.ANAEROBIC_HEART_RATE_UPPER_LIMIT to "Anaerobic Heart Rate Upper Limit",
        BleGattCharacteristicUuids.ANAEROBIC_THRESHOLD to "Anaerobic Threshold",
        BleGattCharacteristicUuids.AEROBIC_HEART_RATE_UPPER_LIMIT to "Aerobic Heart Rate Upper Limit",
        BleGattCharacteristicUuids.DATE_OF_BIRTH to "Date of Birth",
        BleGattCharacteristicUuids.DATE_OF_THRESHOLD_ASSESSMENT to "Date of Threshold Assessment",
        BleGattCharacteristicUuids.EMAIL_ADDRESS to "Email Address",
        BleGattCharacteristicUuids.FAT_BURN_HEART_RATE_LOWER_LIMIT to "Fat Burn Heart Rate Lower Limit",
        BleGattCharacteristicUuids.FAT_BURN_HEART_RATE_UPPER_LIMIT to "Fat Burn Heart Rate Upper Limit",
        BleGattCharacteristicUuids.FIRST_NAME to "First Name",
        BleGattCharacteristicUuids.FIVE_ZONE_HEART_RATE_LIMITS to "Five Zone Heart Rate Limits",
        BleGattCharacteristicUuids.GENDER to "Gender",
        BleGattCharacteristicUuids.HEART_RATE_MAX to "Heart Rate Max",
        BleGattCharacteristicUuids.HEIGHT to "Height",
        BleGattCharacteristicUuids.HIP_CIRCUMFERENCE to "Hip Circumference",
        BleGattCharacteristicUuids.LAST_NAME to "Last Name",
        BleGattCharacteristicUuids.MAXIMUM_RECOMMENDED_HEART_RATE to "Maximum Recommended Heart Rate",
        BleGattCharacteristicUuids.RESTING_HEART_RATE to "Resting Heart Rate",
        BleGattCharacteristicUuids.SPORT_TYPE_FOR_AEROBIC_AND_ANAEROBIC_THRESHOLDS to "Short Type For Aerobic And Anaerobic Thresholds",
        BleGattCharacteristicUuids.THREE_ZONE_HEART_RATE_LIMITS to "Three Zone Heart Rate Limits",
        BleGattCharacteristicUuids.TWO_ZONE_HEART_RATE_LIMIT to "Two Zone Heart Rate Limit",
        BleGattCharacteristicUuids.VO2_MAX to "VO2 Max",
        BleGattCharacteristicUuids.WAIST_CIRCUMFERENCE to "Waist Circumference",
        BleGattCharacteristicUuids.WEIGHT to "Weight",
        BleGattCharacteristicUuids.BOND_MANAGEMENT_FEATURE to "Bond Managerment Feature",
        BleGattCharacteristicUuids.CENTRAL_ADDRESS_RESOLUTION to "Central Address Resolution",
        BleGattCharacteristicUuids.CGM_MEASUREMENT to "GCM Measurement",
        BleGattCharacteristicUuids.CGM_FEATURE to "GCM Feature",
        BleGattCharacteristicUuids.CGM_STATUS to "GCM Status",
        BleGattCharacteristicUuids.CGM_SESSION_START_TIME to "GCM Session Start Time",
        BleGattCharacteristicUuids.CGM_SESSION_RUN_TIME to "GCM Session Run Time",
        BleGattCharacteristicUuids.CGM_SPECIFIC_OPS_CONTROL_POINT to "GCM Specific Ops Control Point",
        BleGattCharacteristicUuids.INDOOR_POSITIONING_CONFIGURATION to "Indoor Positioning Configuration",
        BleGattCharacteristicUuids.LATITUDE to "Latitude",
        BleGattCharacteristicUuids.LONGITUDE to "Longitude",
        BleGattCharacteristicUuids.LOCAL_NORTH_COORDINATE to "Local North Coordinate",
        BleGattCharacteristicUuids.LOCAL_EAST_COORDINATE to "Local East Coordinate",
        BleGattCharacteristicUuids.FLOOR_NUMBER to "Floor Number",
        BleGattCharacteristicUuids.ALTITUDE to "Altitude",
        BleGattCharacteristicUuids.DATABASE_CHANGE_INCREMENT to "Database Change Increment",
        BleGattCharacteristicUuids.USER_INDEX to "User Index",
        BleGattCharacteristicUuids.BODY_COMPOSITION_FEATURE to "Body Composition Feature",
        BleGattCharacteristicUuids.BODY_COMPOSITION_MEASUREMENT to "Body Composition Measurement",
        BleGattCharacteristicUuids.WEIGHT_MEASUREMENT to "Weight Measurement",
        BleGattCharacteristicUuids.WEIGHT_SCALE_FEATURE to "Weight Scale Feature",
        BleGattCharacteristicUuids.USER_CONTROL_POINT to "User Control Point",
        BleGattCharacteristicUuids.MAGNETIC_FLUX_DENSITY_2D to "Magnetic Flux Density 2D",
        BleGattCharacteristicUuids.MAGNETIC_FLUX_DENSITY_3D to "Magnetic Flux Density 3D",
        BleGattCharacteristicUuids.LANGUAGE to "Language",
        BleGattCharacteristicUuids.BAROMETRIC_PRESSURE_TREND to "Barometric Pressure Trend",
        BleGattCharacteristicUuids.BOND_MANAGEMENT_CONTROL_POINT to "Bond Management Control Point",
        BleGattCharacteristicUuids.UNCERTAINTY to "Uncertainty",
        BleGattCharacteristicUuids.LOCATION_NAME to "Location Name",
        BleGattCharacteristicUuids.URI to "Ui",
        BleGattCharacteristicUuids.HTTP_HEADERS to "Http Headers",
        BleGattCharacteristicUuids.HTTP_STATUS_CODE to "Http Status Code",
        BleGattCharacteristicUuids.HTTP_ENTITY_BODY to "Http Entity Body",
        BleGattCharacteristicUuids.HTTP_CONTROL_POINT to "Http Control Point",
        BleGattCharacteristicUuids.HTTPS_SECURITY to "Https Security",
        BleGattCharacteristicUuids.TDS_CONTROL_POINT to "Tds Control Point",
        BleGattCharacteristicUuids.OTS_FEATURE to "Ots Feature",
        BleGattCharacteristicUuids.OBJECT_NAME to "Object Name",
        BleGattCharacteristicUuids.OBJECT_TYPE to "Object Type",
        BleGattCharacteristicUuids.OBJECT_SIZE to "Object Size",
        BleGattCharacteristicUuids.OBJECT_FIRST_CREATED to "Object First Created",
        BleGattCharacteristicUuids.OBJECT_LAST_MODIFIED to "Object Last Modified",
        BleGattCharacteristicUuids.OBJECT_ID to "Object Id",
        BleGattCharacteristicUuids.OBJECT_PROPERTIES to "Object Properties",
        BleGattCharacteristicUuids.OBJECT_ACTION_CONTROL_POINT to "Object Action Control Point",
        BleGattCharacteristicUuids.OBJECT_LIST_CONTROL_POINT to "Object List Control Point",
        BleGattCharacteristicUuids.OBJECT_LIST_FILTER to "Object List Filter",
        BleGattCharacteristicUuids.OBJECT_CHANGED to "Object Changed",
        BleGattCharacteristicUuids.RESOLVABLE_PRIVATE_ADDRESS_ONLY to "Resolvable Private Address Only",
        BleGattCharacteristicUuids.UNSPECIFIED to "Unspecified",
        BleGattCharacteristicUuids.DIRECTORY_LISTING to "Directory Listing",
        BleGattCharacteristicUuids.FITNESS_MACHINE_FEATURE to "Fitness Machine Feature",
        BleGattCharacteristicUuids.TREADMILL_DATA to "Treadmill Data",
        BleGattCharacteristicUuids.CROSS_TRAINER_DATA to "Cross Trainer Data",
        BleGattCharacteristicUuids.STEP_CLIMBER_DATA to "Step Climber Data",
        BleGattCharacteristicUuids.STAIR_CLIMBER_DATA to "Stair Climber Data",
        BleGattCharacteristicUuids.ROWER_DATA to "Rower Data",
        BleGattCharacteristicUuids.INDOOR_BIKE_DATA to "Indoor Bike Data",
        BleGattCharacteristicUuids.TRAINING_STATUS to "Training Status",
        BleGattCharacteristicUuids.SUPPORTED_SPEED_RANGE to "Supported Speed Range",
        BleGattCharacteristicUuids.SUPPORTED_INCLINATION_RANGE to "Supported Inclination Range",
        BleGattCharacteristicUuids.SUPPORTED_RESISTANCE_LEVEL_RANGE to "Supported Resistance Level Range",
        BleGattCharacteristicUuids.SUPPORTED_HEART_RATE_RANGE to "Supported Heart Rate Range",
        BleGattCharacteristicUuids.SUPPORTED_POWER_RANGE to "Supported Power Range",
        BleGattCharacteristicUuids.FITNESS_MACHINE_CONTROL_POINT to "Fitness Machine Control Point",
        BleGattCharacteristicUuids.FITNESS_MACHINE_STATUS to "Fitness Machine Status",
        BleGattCharacteristicUuids.MESH_PROVISIONING_DATA_IN to "Mesh Provisioning Date in",
        BleGattCharacteristicUuids.MESH_PROVISIONING_DATA_OUT to "Mesh Provisioning Date out",
        BleGattCharacteristicUuids.MESH_PROXY_DATA_IN to "Mesh Proxy Data Int",
        BleGattCharacteristicUuids.MESH_PROXY_DATA_OUT to "Mesh Proxy Data Out",
        BleGattCharacteristicUuids.AVERAGE_CURRENT to "Average Current",
        BleGattCharacteristicUuids.AVERAGE_VOLTAGE to "Average Voltage",
        BleGattCharacteristicUuids.BOOLEAN to "Boolean",
        BleGattCharacteristicUuids.CHROMATIC_DISTANCE_FROM_PLANCKIAN to "Chromatic Distance From Plackian",
        BleGattCharacteristicUuids.CHROMATICITY_COORDINATES to "Chromaticity Coordinates",
        BleGattCharacteristicUuids.CHROMATICITY_IN_CCT_AND_DUV_VALUES to "Chromaticity in Cct And Duv Names",
        BleGattCharacteristicUuids.CHROMATICITY_TOLERANCE to "Chromaticity Tolerance",
        BleGattCharacteristicUuids.CIE_13_3_1995_COLOR_RENDERING_INDEX to "Cie 13 3 1995 Color Rendering Index",
        BleGattCharacteristicUuids.COEFFICIENT to "Coefficient",
        BleGattCharacteristicUuids.CORRELATED_COLOR_TEMPERATURE to "Correlated Color Temperature",
        BleGattCharacteristicUuids.COUNT_16 to "Count 16",
        BleGattCharacteristicUuids.COUNT_24 to "Count 24",
        BleGattCharacteristicUuids.COUNTRY_CODE to "Country Code",
        BleGattCharacteristicUuids.DATE_UTC to "Date Utc",
        BleGattCharacteristicUuids.ELECTRIC_CURRENT to "Electric Current",
        BleGattCharacteristicUuids.ELECTRIC_CURRENT_RANGE to "Electric Current Range",
        BleGattCharacteristicUuids.ELECTRIC_CURRENT_SPECIFICATION to "Electric Current Specification",
        BleGattCharacteristicUuids.ELECTRIC_CURRENT_STATISTICS to "Electric Current Statistics",
        BleGattCharacteristicUuids.ENERGY to "Energy",
        BleGattCharacteristicUuids.ENERGY_IN_A_PERIOD_OF_DAY to "Energy In A Period Of Day",
        BleGattCharacteristicUuids.EVENT_STATISTICS to "Event Statistics",
        BleGattCharacteristicUuids.FIXED_STRING_16 to "Fixed String 16",
        BleGattCharacteristicUuids.FIXED_STRING_24 to "Fixed String 24",
        BleGattCharacteristicUuids.FIXED_STRING_36 to "Fixed String 36",
        BleGattCharacteristicUuids.FIXED_STRING_8 to "Fixed String 8",
        BleGattCharacteristicUuids.GENERIC_LEVEL to "Generic Level",
        BleGattCharacteristicUuids.GLOBAL_TRADE_ITEM_NUMBER to "Global Trade Item Number",
        BleGattCharacteristicUuids.ILLUMINANCE to "Illuminance",
        BleGattCharacteristicUuids.LUMINOUS_EFFICACY to "Luminous Efficacy",
        BleGattCharacteristicUuids.LUMINOUS_ENERGY to "Luminous Energy",
        BleGattCharacteristicUuids.LUMINOUS_EXPOSURE to "Luminous Exposure",
        BleGattCharacteristicUuids.LUMINOUS_FLUX to "Luminous Flux",
        BleGattCharacteristicUuids.LUMINOUS_FLUX_RANGE to "Luminous Flux Range",
        BleGattCharacteristicUuids.LUMINOUS_INTENSITY to "Luminous Intensity",
        BleGattCharacteristicUuids.MASS_FLOW to "Mass Flow",
        BleGattCharacteristicUuids.PERCEIVED_LIGHTNESS to "Perceived Lightness",
        BleGattCharacteristicUuids.PERCENTAGE_8 to "Percentage 8",
        BleGattCharacteristicUuids.POWER to "Power",
        BleGattCharacteristicUuids.POWER_SPECIFICATION to "Power Specification",
        BleGattCharacteristicUuids.RELATIVE_RUNTIME_IN_A_CURRENT_RANGE to "Relative Runtime In A Current Range",
        BleGattCharacteristicUuids.RELATIVE_RUNTIME_IN_A_GENERIC_LEVEL_RANGE to "Relative Runtime In A Generic Level Range",
        BleGattCharacteristicUuids.RELATIVE_VALUE_IN_A_VOLTAGE_RANGE to "Relative Value In A Voltage Range",
        BleGattCharacteristicUuids.RELATIVE_VALUE_IN_AN_ILLUMINANCE_RANGE to "Relative Value In An Illuminance Range",
        BleGattCharacteristicUuids.RELATIVE_VALUE_IN_A_PERIOD_OF_DAY to "Relative Value In A Period Of Day",
        BleGattCharacteristicUuids.RELATIVE_VALUE_IN_A_TEMPERATURE_RANGE to "Relative Value In A Temperature Range",
        BleGattCharacteristicUuids.TEMPERATURE_8 to "Temperature 8",
        BleGattCharacteristicUuids.TEMPERATURE_8_IN_A_PERIOD_OF_DAY to "Temperature 8 In A Period Of Day",
        BleGattCharacteristicUuids.TEMPERATURE_8_STATISTICS to "Temperature 8 Statistics",
        BleGattCharacteristicUuids.TEMPERATURE_RANGE to "Temperature Range",
        BleGattCharacteristicUuids.TEMPERATURE_STATISTICS to "Temperature Statistics",
        BleGattCharacteristicUuids.TIME_DECIHOUR_8 to "Time Decihour 8",
        BleGattCharacteristicUuids.TIME_EXPONENTIAL_8 to "Time Exponential 8",
        BleGattCharacteristicUuids.TIME_HOUR_24 to "Time Hour 24",
        BleGattCharacteristicUuids.TIME_MILLISECOND_24 to "Time Millisecond 24",
        BleGattCharacteristicUuids.TIME_SECOND_16 to "Time Second 16",
        BleGattCharacteristicUuids.TIME_SECOND_8 to "Time Second 8",
        BleGattCharacteristicUuids.VOLTAGE to "Voltage",
        BleGattCharacteristicUuids.VOLTAGE_SPECIFICATION to "Voltage Specification",
        BleGattCharacteristicUuids.VOLTAGE_STATISTICS to "Voltage Statistics",
        BleGattCharacteristicUuids.VOLUME_FLOW to "Volume Flow",
        BleGattCharacteristicUuids.CHROMATICITY_COORDINATE to "Chromaticity Coordinate",
        BleGattCharacteristicUuids.RC_FEATURE to "Rc Feature",
        BleGattCharacteristicUuids.RC_SETTINGS to "Rc Settings",
        BleGattCharacteristicUuids.RECONNECTION_CONFIGURATION_CONTROL_POINT to "Reconnection Configuration Control Point",
        BleGattCharacteristicUuids.IDD_STATUS_CHANGED to "Idd Status Changed",
        BleGattCharacteristicUuids.IDD_STATUS to "Idd Status",
        BleGattCharacteristicUuids.IDD_ANNUNCIATION_STATUS to "Idd Annunciation Status",
        BleGattCharacteristicUuids.IDD_FEATURES to "Idd Features",
        BleGattCharacteristicUuids.IDD_STATUS_READER_CONTROL_POINT to "Idd Status Reader Control Point",
        BleGattCharacteristicUuids.IDD_COMMAND_CONTROL_POINT to "Idd Command Control Point",
        BleGattCharacteristicUuids.IDD_COMMAND_DATA to "Idd Command Data",
        BleGattCharacteristicUuids.IDD_RECORD_ACCESS_CONTROL_POINT to "Idd Record Access Control Point",
        BleGattCharacteristicUuids.IDD_HISTORY_DATA to "Idd History Date",
        BleGattCharacteristicUuids.CLIENT_SUPPORTED_FEATURES to "Client Supported Features",
        BleGattCharacteristicUuids.DATABASE_HASH to "Database Hash",
        BleGattCharacteristicUuids.BSS_CONTROL_POINT to "Bss Control Point",
        BleGattCharacteristicUuids.BSS_RESPONSE to "Bss Response",
        BleGattCharacteristicUuids.EMERGENCY_ID to "Emergency Id",
        BleGattCharacteristicUuids.EMERGENCY_TEXT to "Emergency Text",
        BleGattCharacteristicUuids.ENHANCED_BLOOD_PRESSURE_MEASUREMENT to "Enhanced Blood Pressure Measurement",
        BleGattCharacteristicUuids.ENHANCED_INTERMEDIATE_CUFF_PRESSURE to "Enhanced Intermediate Cuff Pressure",
        BleGattCharacteristicUuids.BLOOD_PRESSURE_RECORD to "Blood Pressure",
        BleGattCharacteristicUuids.BR_EDR_HANDOVER_DATA to "Br Edr Handover Data",
        BleGattCharacteristicUuids.BLUETOOTH_SIG_DATA to "Bluetooth Sig Data",
        BleGattCharacteristicUuids.SERVER_SUPPORTED_FEATURES to "Server Supported Features",
        BleGattCharacteristicUuids.PHYSICAL_ACTIVITY_MONITOR_FEATURES to "Physical",
        BleGattCharacteristicUuids.GENERAL_ACTIVITY_INSTANTANEOUS_DATA to "General Activity Instantaneous Data",
        BleGattCharacteristicUuids.GENERAL_ACTIVITY_SUMMARY_DATA to "General Activity Summary Data",
        BleGattCharacteristicUuids.CARDIORESPIRATORY_ACTIVITY_INSTANTANEOUS_DATA to "Cardiorespiratory Activity Instantaneous Data",
        BleGattCharacteristicUuids.CARDIORESPIRATORY_ACTIVITY_SUMMARY_DATA to "Cardiorespiratory Activity Summary Data",
        BleGattCharacteristicUuids.STEP_COUNTER_ACTIVITY_SUMMARY_DATA to "Step Counter Activity Summary Data",
        BleGattCharacteristicUuids.SLEEP_ACTIVITY_INSTANTANEOUS_DATA to "Sleep Activity Instantaneous Data",
        BleGattCharacteristicUuids.SLEEP_ACTIVITY_SUMMARY_DATA to "Sleep Activity Summary Data",
        BleGattCharacteristicUuids.PHYSICAL_ACTIVITY_MONITOR_CONTROL_POINT to "2B43",
        BleGattCharacteristicUuids.CURRENT_SESSION to "Current Session",
        BleGattCharacteristicUuids.SESSION to "Session",
        BleGattCharacteristicUuids.PREFERRED_UNITS to "Preferred Units",
        BleGattCharacteristicUuids.HIGH_RESOLUTION_HEIGHT to "High Resolution Height",
        BleGattCharacteristicUuids.MIDDLE_NAME to "Middle Name",
        BleGattCharacteristicUuids.STRIDE_LENGTH to "Stride Length",
        BleGattCharacteristicUuids.HANDEDNESS to "Handedness",
        BleGattCharacteristicUuids.DEVICE_WEARING_POSITION to "Device Wearing Position",
        BleGattCharacteristicUuids.FOUR_ZONE_HEART_RATE_LIMITS to "Four Zone Heart Rate Limits",
        BleGattCharacteristicUuids.HIGH_INTENSITY_EXERCISE_THRESHOLD to "High Intensity Exercise Threshold",
        BleGattCharacteristicUuids.ACTIVITY_GOAL to "Activity Goal",
        BleGattCharacteristicUuids.SEDENTARY_INTERVAL_NOTIFICATION to "Sedentary Interval Notification",
        BleGattCharacteristicUuids.CALORIC_INTAKE to "Caloric Intake",
        BleGattCharacteristicUuids.AUDIO_INPUT_STATE to "Audio Input State",
        BleGattCharacteristicUuids.GAIN_SETTINGS_ATTRIBUTE to "Gain Settings Attribute",
        BleGattCharacteristicUuids.AUDIO_INPUT_TYPE to "Audio Input Type",
        BleGattCharacteristicUuids.AUDIO_INPUT_STATUS to "Audion Input Status",
        BleGattCharacteristicUuids.AUDIO_INPUT_CONTROL_POINT to "Audio Input Control Point",
        BleGattCharacteristicUuids.AUDIO_INPUT_DESCRIPTION to "Audio Input Description",
        BleGattCharacteristicUuids.VOLUME_STATE to "Volume State",
        BleGattCharacteristicUuids.VOLUME_CONTROL_POINT to "Volume Control Point",
        BleGattCharacteristicUuids.VOLUME_FLAGS to "Volume Flags",
        BleGattCharacteristicUuids.OFFSET_STATE to "Offset State",
        BleGattCharacteristicUuids.AUDIO_LOCATION to "Audio Location",
        BleGattCharacteristicUuids.VOLUME_OFFSET_CONTROL_POINT to "Volume Offset Control Point",
        BleGattCharacteristicUuids.AUDIO_OUTPUT_DESCRIPTION to "Audio Output Description",
        BleGattCharacteristicUuids.DEVICE_TIME_FEATURE to "Device Time Feature",
        BleGattCharacteristicUuids.DEVICE_TIME_PARAMETERS to "Device Time Parameters",
        BleGattCharacteristicUuids.DEVICE_TIME to "Device Time",
        BleGattCharacteristicUuids.DEVICE_TIME_CONTROL_POINT to "Device Time Control Point",
        BleGattCharacteristicUuids.TIME_CHANGE_LOG_DATA to "Time Change Log Data",
    )
}

/**
 * The bluetooth gatt descriptor uuids for logging purposes.
 */
internal val gattDescriptorUuids by lazy {
    mapOf(
        BleGattDescriptorUuids.CHARACTERISTIC_EXTENDED_PROPERTIES to "Characteristic Extended Properties",
        BleGattDescriptorUuids.CHARACTERISTIC_USER_DESCRIPTION to "Characteristic User Description",
        BleGattDescriptorUuids.CLIENT_CHARACTERISTIC_CONFIGURATION to "Client Characteristic Configuration",
        BleGattDescriptorUuids.SERVER_CHARACTERISTIC_CONFIGURATION to "Server Characteristic Configuration",
        BleGattDescriptorUuids.CHARACTERISTIC_PRESENTATION_FORMAT to "Characteristic Presentation Format",
        BleGattDescriptorUuids.CHARACTERISTIC_AGGREGATE_FORMAT to "Characteristic Aggregate Format",
        BleGattDescriptorUuids.VALID_RANGE to "Valid Range",
        BleGattDescriptorUuids.EXTERNAL_REPORT_REFERENCE to "External Report Reference",
        BleGattDescriptorUuids.REPORT_REFERENCE to "Report Reference",
        BleGattDescriptorUuids.NUMBER_OF_DIGITALS to "Number of Digitals",
        BleGattDescriptorUuids.VALUE_TRIGGER_SETTING to "Value Trigger Setting",
        BleGattDescriptorUuids.ENVIRONMENTAL_SENSING_CONFIGURATION to "Environmental Sensing Configuration",
        BleGattDescriptorUuids.ENVIRONMENTAL_SENSING_MEASUREMENT to "Environmental Sensing Measurement",
        BleGattDescriptorUuids.ENVIRONMENTAL_SENSING_TRIGGER_SETTING to "Environmental Sensing Trigger Setting",
        BleGattDescriptorUuids.TIME_TRIGGER_SETTING to "Time Trigger Setting",
        BleGattDescriptorUuids.COMPLETE_BR_EDR_TRANSPORT_BLOCK_DATA to "Complete Br Edr Transport Block Data",
    )
}

internal val bleCompanies by lazy {
    mapOf(
        0 to "Ericsson Technology Licensing",
        1 to "Nokia Mobile Phones",
        2 to "Intel Corp.",
        3 to "IBM Corp.",
        4 to "Toshiba Corp.",
        5 to "3Com",
        6 to "Microsoft",
        7 to "Lucent",
        8 to "Motorola",
        9 to "Infineon Technologies AG",
        10 to "Qualcomm Technologies International, Ltd. (QTIL)",
        11 to "Silicon Wave",
        12 to "Digianswer A/S",
        13 to "Texas Instruments Inc.",
        14 to "Parthus Technologies Inc.",
        15 to "Broadcom Corporation",
        16 to "Mitel Semiconductor",
        17 to "Widcomm, Inc.",
        18 to "Zeevo, Inc.",
        19 to "Atmel Corporation",
        20 to "Mitsubishi Electric Corporation",
        21 to "RTX Telecom A/S",
        22 to "KC Technology Inc.",
        23 to "Newlogic",
        24 to "Transilica, Inc.",
        25 to "Rohde & Schwarz GmbH & Co. KG",
        26 to "TTPCom Limited",
        27 to "Signia Technologies, Inc.",
        28 to "Conexant Systems Inc.",
        29 to "Qualcomm",
        30 to "Inventel",
        31 to "AVM Berlin",
        32 to "BandSpeed, Inc.",
        33 to "Mansella Ltd",
        34 to "NEC Corporation",
        35 to "WavePlus Technology Co., Ltd.",
        36 to "Alcatel",
        37 to "NXP Semiconductors (formerly Philips Semiconductors)",
        38 to "C Technologies",
        39 to "Open Interface",
        40 to "R F Micro Devices",
        41 to "Hitachi Ltd",
        42 to "Symbol Technologies, Inc.",
        43 to "Tenovis",
        44 to "Macronix International Co. Ltd.",
        45 to "GCT Semiconductor",
        46 to "Norwood Systems",
        47 to "MewTel Technology Inc.",
        48 to "ST Microelectronics",
        49 to "Synopsys, Inc.",
        50 to "Red-M (Communications) Ltd",
        51 to "Commil Ltd",
        52 to "Computer Access Technology Corporation (CATC)",
        53 to "Eclipse (HQ Espana) S.L.",
        54 to "Renesas Electronics Corporation",
        55 to "Mobilian Corporation",
        56 to "Syntronix Corporation",
        57 to "Integrated System Solution Corp.",
        58 to "Panasonic Corporation (formerly Matsushita Electric Industrial Co., Ltd.)",
        59 to "Gennum Corporation",
        60 to "BlackBerry Limited  (formerly Research In Motion)",
        61 to "IPextreme, Inc.",
        62 to "Systems and Chips, Inc",
        63 to "Bluetooth SIG, Inc",
        64 to "Seiko Epson Corporation",
        65 to "Integrated Silicon Solution Taiwan, Inc.",
        66 to "CONWISE Technology Corporation Ltd",
        67 to "PARROT AUTOMOTIVE SAS",
        68 to "Socket Mobile",
        69 to "Atheros Communications, Inc.",
        70 to "MediaTek, Inc.",
        71 to "Bluegiga",
        72 to "Marvell Technology Group Ltd.",
        73 to "3DSP Corporation",
        74 to "Accel Semiconductor Ltd.",
        75 to "Continental Automotive Systems",
        76 to "Apple, Inc.",
        77 to "Staccato Communications, Inc.",
        78 to "Avago Technologies",
        79 to "APT Ltd.",
        80 to "SiRF Technology, Inc.",
        81 to "Tzero Technologies, Inc.",
        82 to "J&M Corporation",
        83 to "Free2move AB",
        84 to "3DiJoy Corporation",
        85 to "Plantronics, Inc.",
        86 to "Sony Ericsson Mobile Communications",
        87 to "Harman International Industries, Inc.",
        88 to "Vizio, Inc.",
        89 to "Nordic Semiconductor ASA",
        90 to "EM Microelectronic-Marin SA",
        91 to "Ralink Technology Corporation",
        92 to "Belkin International, Inc.",
        93 to "Realtek Semiconductor Corporation",
        94 to "Stonestreet One, LLC",
        95 to "Wicentric, Inc.",
        96 to "RivieraWaves S.A.S",
        97 to "RDA Microelectronics",
        98 to "Gibson Guitars",
        99 to "MiCommand Inc.",
        100 to "Band XI International, LLC",
        101 to "Hewlett-Packard Company",
        102 to "9Solutions Oy",
        103 to "GN Netcom A/S",
        104 to "General Motors",
        105 to "A&D Engineering, Inc.",
        106 to "MindTree Ltd.",
        107 to "Polar Electro OY",
        108 to "Beautiful Enterprise Co., Ltd.",
        109 to "BriarTek, Inc",
        110 to "Summit Data Communications, Inc.",
        111 to "Sound ID",
        112 to "Monster, LLC",
        113 to "connectBlue AB",
        114 to "ShangHai Super Smart Electronics Co. Ltd.",
        115 to "Group Sense Ltd.",
        116 to "Zomm, LLC",
        117 to "Samsung Electronics Co. Ltd.",
        118 to "Creative Technology Ltd.",
        119 to "Laird Technologies",
        120 to "Nike, Inc.",
        121 to "lesswire AG",
        122 to "MStar Semiconductor, Inc.",
        123 to "Hanlynn Technologies",
        124 to "A & R Cambridge",
        125 to "Seers Technology Co., Ltd.",
        126 to "Sports Tracking Technologies Ltd.",
        127 to "Autonet Mobile",
        128 to "DeLorme Publishing Company, Inc.",
        129 to "WuXi Vimicro",
        130 to "Sennheiser Communications A/S",
        131 to "TimeKeeping Systems, Inc.",
        132 to "Ludus Helsinki Ltd.",
        133 to "BlueRadios, Inc.",
        134 to "Equinux AG",
        135 to "Garmin International, Inc.",
        136 to "Ecotest",
        137 to "GN ReSound A/S",
        138 to "Jawbone",
        139 to "Topcon Positioning Systems, LLC",
        140 to "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)",
        141 to "Zscan Software",
        142 to "Quintic Corp",
        143 to "Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH)",
        144 to "Funai Electric Co., Ltd.",
        145 to "Advanced PANMOBIL systems GmbH & Co. KG",
        146 to "ThinkOptics, Inc.",
        147 to "Universal Electronics, Inc.",
        148 to "Airoha Technology Corp.",
        149 to "NEC Lighting, Ltd.",
        150 to "ODM Technology, Inc.",
        151 to "ConnecteDevice Ltd.",
        152 to "zero1.tv GmbH",
        153 to "i.Tech Dynamic Global Distribution Ltd.",
        154 to "Alpwise",
        155 to "Jiangsu Toppower Automotive Electronics Co., Ltd.",
        156 to "Colorfy, Inc.",
        157 to "Geoforce Inc.",
        158 to "Bose Corporation",
        159 to "Suunto Oy",
        160 to "Kensington Computer Products Group",
        161 to "SR-Medizinelektronik",
        162 to "Vertu Corporation Limited",
        163 to "Meta Watch Ltd.",
        164 to "LINAK A/S",
        165 to "OTL Dynamics LLC",
        166 to "Panda Ocean Inc.",
        167 to "Visteon Corporation",
        168 to "ARP Devices Limited",
        169 to "MARELLI EUROPE S.P.A. (formerly Magneti Marelli S.p.A.)",
        170 to "CAEN RFID srl",
        171 to "Ingenieur-Systemgruppe Zahn GmbH",
        172 to "Green Throttle Games",
        173 to "Peter Systemtechnik GmbH",
        174 to "Omegawave Oy",
        175 to "Cinetix",
        176 to "Passif Semiconductor Corp",
        177 to "Saris Cycling Group, Inc",
        178 to "Bekey A/S",
        179 to "Clarinox Technologies Pty. Ltd.",
        180 to "BDE Technology Co., Ltd.",
        181 to "Swirl Networks",
        182 to "Meso international",
        183 to "TreLab Ltd",
        184 to "Qualcomm Innovation Center, Inc. (QuIC)",
        185 to "Johnson Controls, Inc.",
        186 to "Starkey Laboratories Inc.",
        187 to "S-Power Electronics Limited",
        188 to "Ace Sensor Inc",
        189 to "Aplix Corporation",
        190 to "AAMP of America",
        191 to "Stalmart Technology Limited",
        192 to "AMICCOM Electronics Corporation",
        193 to "Shenzhen Excelsecu Data Technology Co.,Ltd",
        194 to "Geneq Inc.",
        195 to "adidas AG",
        196 to "LG Electronics​",
        197 to "Onset Computer Corporation",
        198 to "Selfly BV",
        199 to "Quuppa Oy.",
        200 to "GeLo Inc",
        201 to "Evluma",
        202 to "MC10",
        203 to "Binauric SE",
        204 to "Beats Electronics",
        205 to "Microchip Technology Inc.",
        206 to "Elgato Systems GmbH",
        207 to "ARCHOS SA",
        208 to "Dexcom, Inc.",
        209 to "Polar Electro Europe B.V.",
        210 to "Dialog Semiconductor B.V.",
        211 to "Taixingbang Technology (HK) Co,. LTD.",
        212 to "Kawantech",
        213 to "Austco Communication Systems",
        214 to "Timex Group USA, Inc.",
        215 to "Qualcomm Technologies, Inc.",
        216 to "Qualcomm Connected Experiences, Inc.",
        217 to "Voyetra Turtle Beach",
        218 to "txtr GmbH",
        219 to "Biosentronics",
        220 to "Procter & Gamble",
        221 to "Hosiden Corporation",
        222 to "Muzik LLC",
        223 to "Misfit Wearables Corp",
        224 to "Google",
        225 to "Danlers Ltd",
        226 to "Semilink Inc",
        227 to "inMusic Brands, Inc",
        228 to "L.S. Research Inc.",
        229 to "Eden Software Consultants Ltd.",
        230 to "Freshtemp",
        231 to "KS Technologies",
        232 to "ACTS Technologies",
        233 to "Vtrack Systems",
        234 to "Nielsen-Kellerman Company",
        235 to "Server Technology Inc.",
        236 to "BioResearch Associates",
        237 to "Jolly Logic, LLC",
        238 to "Above Average Outcomes, Inc.",
        239 to "Bitsplitters GmbH",
        240 to "PayPal, Inc.",
        241 to "Witron Technology Limited",
        242 to "Morse Project Inc.",
        243 to "Kent Displays Inc.",
        244 to "Nautilus Inc.",
        245 to "Smartifier Oy",
        246 to "Elcometer Limited",
        247 to "VSN Technologies, Inc.",
        248 to "AceUni Corp., Ltd.",
        249 to "StickNFind",
        250 to "Crystal Code AB",
        251 to "KOUKAAM a.s.",
        252 to "Delphi Corporation",
        253 to "ValenceTech Limited",
        254 to "Stanley Black and Decker",
        255 to "Typo Products, LLC",
        256 to "TomTom International BV",
        257 to "Fugoo, Inc.",
        258 to "Keiser Corporation",
        259 to "Bang & Olufsen A/S",
        260 to "PLUS Location Systems Pty Ltd",
        261 to "Ubiquitous Computing Technology Corporation",
        262 to "Innovative Yachtter Solutions",
        263 to "William Demant Holding A/S",
        264 to "Chicony Electronics Co., Ltd.",
        265 to "Atus BV",
        266 to "Codegate Ltd",
        267 to "ERi, Inc",
        268 to "Transducers Direct, LLC",
        269 to "DENSO TEN LIMITED (formerly Fujitsu Ten LImited)",
        270 to "Audi AG",
        271 to "HiSilicon Technologies CO., LIMITED",
        272 to "Nippon Seiki Co., Ltd.",
        273 to "Steelseries ApS",
        274 to "Visybl Inc.",
        275 to "Openbrain Technologies, Co., Ltd.",
        276 to "Xensr",
        277 to "e.solutions",
        278 to "10AK Technologies",
        279 to "Wimoto Technologies Inc",
        280 to "Radius Networks, Inc.",
        281 to "Wize Technology Co., Ltd.",
        282 to "Qualcomm Labs, Inc.",
        283 to "Hewlett Packard Enterprise",
        284 to "Baidu",
        285 to "Arendi AG",
        286 to "Skoda Auto a.s.",
        287 to "Volkswagen AG",
        288 to "Porsche AG",
        289 to "Sino Wealth Electronic Ltd.",
        290 to "AirTurn, Inc.",
        291 to "Kinsa, Inc",
        292 to "HID Global",
        293 to "SEAT es",
        294 to "Promethean Ltd.",
        295 to "Salutica Allied Solutions",
        296 to "GPSI Group Pty Ltd",
        297 to "Nimble Devices Oy",
        298 to "Changzhou Yongse Infotech  Co., Ltd.",
        299 to "SportIQ",
        300 to "TEMEC Instruments B.V.",
        301 to "Sony Corporation",
        302 to "ASSA ABLOY",
        303 to "Clarion Co. Inc.",
        304 to "Warehouse Innovations",
        305 to "Cypress Semiconductor",
        306 to "MADS Inc",
        307 to "Blue Maestro Limited",
        308 to "Resolution Products, Ltd.",
        309 to "Aireware LLC",
        310 to "Silvair, Inc.",
        311 to "Prestigio Plaza Ltd.",
        312 to "NTEO Inc.",
        313 to "Focus Systems Corporation",
        314 to "Tencent Holdings Ltd.",
        315 to "Allegion",
        316 to "Murata Manufacturing Co., Ltd.",
        317 to "WirelessWERX",
        318 to "Nod, Inc.",
        319 to "B&B Manufacturing Company",
        320 to "Alpine Electronics (China) Co., Ltd",
        321 to "FedEx Services",
        322 to "Grape Systems Inc.",
        323 to "Bkon Connect",
        324 to "Lintech GmbH",
        325 to "Novatel Wireless",
        326 to "Ciright",
        327 to "Mighty Cast, Inc.",
        328 to "Ambimat Electronics",
        329 to "Perytons Ltd.",
        330 to "Tivoli Audio, LLC",
        331 to "Master Lock",
        332 to "Mesh-Net Ltd",
        333 to "HUIZHOU DESAY SV AUTOMOTIVE CO., LTD.",
        334 to "Tangerine, Inc.",
        335 to "B&W Group Ltd.",
        336 to "Pioneer Corporation",
        337 to "OnBeep",
        338 to "Vernier Software & Technology",
        339 to "ROL Ergo",
        340 to "Pebble Technology",
        341 to "NETATMO",
        342 to "Accumulate AB",
        343 to "Anhui Huami Information Technology Co., Ltd.",
        344 to "Inmite s.r.o.",
        345 to "ChefSteps, Inc.",
        346 to "micas AG",
        347 to "Biomedical Research Ltd.",
        348 to "Pitius Tec S.L.",
        349 to "Estimote, Inc.",
        350 to "Unikey Technologies, Inc.",
        351 to "Timer Cap Co.",
        352 to "AwoX",
        353 to "yikes",
        354 to "MADSGlobalNZ Ltd.",
        355 to "PCH International",
        356 to "Qingdao Yeelink Information Technology Co., Ltd.",
        357 to "Milwaukee Tool (Formally Milwaukee Electric Tools)",
        358 to "MISHIK Pte Ltd",
        359 to "Ascensia Diabetes Care US Inc.",
        360 to "Spicebox LLC",
        361 to "emberlight",
        362 to "Cooper-Atkins Corporation",
        363 to "Qblinks",
        364 to "MYSPHERA",
        365 to "LifeScan Inc",
        366 to "Volantic AB",
        367 to "Podo Labs, Inc",
        368 to "Roche Diabetes Care AG",
        369 to "Amazon.com Services, LLC (formerly Amazon Fulfillment Service)",
        370 to "Connovate Technology Private Limited",
        371 to "Kocomojo, LLC",
        372 to "Everykey Inc.",
        373 to "Dynamic Controls",
        374 to "SentriLock",
        375 to "I-SYST inc.",
        376 to "CASIO COMPUTER CO., LTD.",
        377 to "LAPIS Technology Co., Ltd. formerly LAPIS Semiconductor Co., Ltd.",
        378 to "Telemonitor, Inc.",
        379 to "taskit GmbH",
        380 to "Daimler AG",
        381 to "BatAndCat",
        382 to "BluDotz Ltd",
        383 to "XTel Wireless ApS",
        384 to "Gigaset Communications GmbH",
        385 to "Gecko Health Innovations, Inc.",
        386 to "HOP Ubiquitous",
        387 to "Walt Disney",
        388 to "Nectar",
        389 to "bel'apps LLC",
        390 to "CORE Lighting Ltd",
        391 to "Seraphim Sense Ltd",
        392 to "Unico RBC",
        393 to "Physical Enterprises Inc.",
        394 to "Able Trend Technology Limited",
        395 to "Konica Minolta, Inc.",
        396 to "Wilo SE",
        397 to "Extron Design Services",
        398 to "Fitbit, Inc.",
        399 to "Fireflies Systems",
        400 to "Intelletto Technologies Inc.",
        401 to "FDK CORPORATION",
        402 to "Cloudleaf, Inc",
        403 to "Maveric Automation LLC",
        404 to "Acoustic Stream Corporation",
        405 to "Zuli",
        406 to "Paxton Access Ltd",
        407 to "WiSilica Inc.",
        408 to "VENGIT Korlatolt Felelossegu Tarsasag",
        409 to "SALTO SYSTEMS S.L.",
        410 to "TRON Forum (formerly T-Engine Forum)",
        411 to "CUBETECH s.r.o.",
        412 to "Cokiya Incorporated",
        413 to "CVS Health",
        414 to "Ceruus",
        415 to "Strainstall Ltd",
        416 to "Channel Enterprises (HK) Ltd.",
        417 to "FIAMM",
        418 to "GIGALANE.CO.,LTD",
        419 to "EROAD",
        420 to "Mine Safety Appliances",
        421 to "Icon Health and Fitness",
        422 to "Wille Engineering (formely as Asandoo GmbH)",
        423 to "ENERGOUS CORPORATION",
        424 to "Taobao",
        425 to "Canon Inc.",
        426 to "Geophysical Technology Inc.",
        427 to "Facebook, Inc.",
        428 to "Trividia Health, Inc.",
        429 to "FlightSafety International",
        430 to "Earlens Corporation",
        431 to "Sunrise Micro Devices, Inc.",
        432 to "Star Micronics Co., Ltd.",
        433 to "Netizens Sp. z o.o.",
        434 to "Nymi Inc.",
        435 to "Nytec, Inc.",
        436 to "Trineo Sp. z o.o.",
        437 to "Nest Labs Inc.",
        438 to "LM Technologies Ltd",
        439 to "General Electric Company",
        440 to "i+D3 S.L.",
        441 to "HANA Micron",
        442 to "Stages Cycling LLC",
        443 to "Cochlear Bone Anchored Solutions AB",
        444 to "SenionLab AB",
        445 to "Syszone Co., Ltd",
        446 to "Pulsate Mobile Ltd.",
        447 to "Hong Kong HunterSun Electronic Limited",
        448 to "pironex GmbH",
        449 to "BRADATECH Corp.",
        450 to "Transenergooil AG",
        451 to "Bunch",
        452 to "DME Microelectronics",
        453 to "Bitcraze AB",
        454 to "HASWARE Inc.",
        455 to "Abiogenix Inc.",
        456 to "Poly-Control ApS",
        457 to "Avi-on",
        458 to "Laerdal Medical AS",
        459 to "Fetch My Pet",
        460 to "Sam Labs Ltd.",
        461 to "Chengdu Synwing Technology Ltd",
        462 to "HOUWA SYSTEM DESIGN, k.k.",
        463 to "BSH",
        464 to "Primus Inter Pares Ltd",
        465 to "August Home, Inc",
        466 to "Gill Electronics",
        467 to "Sky Wave Design",
        468 to "Newlab S.r.l.",
        469 to "ELAD srl",
        470 to "G-wearables inc.",
        471 to "Squadrone Systems Inc.",
        472 to "Code Corporation",
        473 to "Savant Systems LLC",
        474 to "Logitech International SA",
        475 to "Innblue Consulting",
        476 to "iParking Ltd.",
        477 to "Koninklijke Philips Electronics N.V.",
        478 to "Minelab Electronics Pty Limited",
        479 to "Bison Group Ltd.",
        480 to "Widex A/S",
        481 to "Jolla Ltd",
        482 to "Lectronix, Inc.",
        483 to "Caterpillar Inc",
        484 to "Freedom Innovations",
        485 to "Dynamic Devices Ltd",
        486 to "Technology Solutions (UK) Ltd",
        487 to "IPS Group Inc.",
        488 to "STIR",
        489 to "Sano, Inc.",
        490 to "Advanced Application Design, Inc.",
        491 to "AutoMap LLC",
        492 to "Spreadtrum Communications Shanghai Ltd",
        493 to "CuteCircuit LTD",
        494 to "Valeo Service",
        495 to "Fullpower Technologies, Inc.",
        496 to "KloudNation",
        497 to "Zebra Technologies Corporation",
        498 to "Itron, Inc.",
        499 to "The University of Tokyo",
        500 to "UTC Fire and Security",
        501 to "Cool Webthings Limited",
        502 to "DJO Global",
        503 to "Gelliner Limited",
        504 to "Anyka (Guangzhou) Microelectronics Technology Co, LTD",
        505 to "Medtronic Inc.",
        506 to "Gozio Inc.",
        507 to "Form Lifting, LLC",
        508 to "Wahoo Fitness, LLC",
        509 to "Kontakt Micro-Location Sp. z o.o.",
        510 to "Radio Systems Corporation",
        511 to "Freescale Semiconductor, Inc.",
        512 to "Verifone Systems Pte Ltd. Taiwan Branch",
        513 to "AR Timing",
        514 to "Rigado LLC",
        515 to "Kemppi Oy",
        516 to "Tapcentive Inc.",
        517 to "Smartbotics Inc.",
        518 to "Otter Products, LLC",
        519 to "STEMP Inc.",
        520 to "LumiGeek LLC",
        521 to "InvisionHeart Inc.",
        522 to "Macnica Inc.",
        523 to "Jaguar Land Rover Limited",
        524 to "CoroWare Technologies, Inc",
        525 to "Simplo Technology Co., LTD",
        526 to "Omron Healthcare Co., LTD",
        527 to "Comodule GMBH",
        528 to "ikeGPS",
        529 to "Telink Semiconductor Co. Ltd",
        530 to "Interplan Co., Ltd",
        531 to "Wyler AG",
        532 to "IK Multimedia Production srl",
        533 to "Lukoton Experience Oy",
        534 to "MTI Ltd",
        535 to "Tech4home, Lda",
        536 to "Hiotech AB",
        537 to "DOTT Limited",
        538 to "Blue Speck Labs, LLC",
        539 to "Cisco Systems, Inc",
        540 to "Mobicomm Inc",
        541 to "Edamic",
        542 to "Goodnet, Ltd",
        543 to "Luster Leaf Products  Inc",
        544 to "Manus Machina BV",
        545 to "Mobiquity Networks Inc",
        546 to "Praxis Dynamics",
        547 to "Philip Morris Products S.A.",
        548 to "Comarch SA",
        549 to "Nestlé Nespresso S.A.",
        550 to "Merlinia A/S",
        551 to "LifeBEAM Technologies",
        552 to "Twocanoes Labs, LLC",
        553 to "Muoverti Limited",
        554 to "Stamer Musikanlagen GMBH",
        555 to "Tesla Motors",
        556 to "Pharynks Corporation",
        557 to "Lupine",
        558 to "Siemens AG",
        559 to "Huami (Shanghai) Culture Communication CO., LTD",
        560 to "Foster Electric Company, Ltd",
        561 to "ETA SA",
        562 to "x-Senso Solutions Kft",
        563 to "Shenzhen SuLong Communication Ltd",
        564 to "FengFan (BeiJing) Technology Co, Ltd",
        565 to "Qrio Inc",
        566 to "Pitpatpet Ltd",
        567 to "MSHeli s.r.l.",
        568 to "Trakm8 Ltd",
        569 to "JIN CO, Ltd",
        570 to "Alatech Tehnology",
        571 to "Beijing CarePulse Electronic Technology Co, Ltd",
        572 to "Awarepoint",
        573 to "ViCentra B.V.",
        574 to "Raven Industries",
        575 to "WaveWare Technologies Inc.",
        576 to "Argenox Technologies",
        577 to "Bragi GmbH",
        578 to "16Lab Inc",
        579 to "Masimo Corp",
        580 to "Iotera Inc",
        581 to "Endress+Hauser",
        582 to "ACKme Networks, Inc.",
        583 to "FiftyThree Inc.",
        584 to "Parker Hannifin Corp",
        585 to "Transcranial Ltd",
        586 to "Uwatec AG",
        587 to "Orlan LLC",
        588 to "Blue Clover Devices",
        589 to "M-Way Solutions GmbH",
        590 to "Microtronics Engineering GmbH",
        591 to "Schneider Schreibgeräte GmbH",
        592 to "Sapphire Circuits LLC",
        593 to "Lumo Bodytech Inc.",
        594 to "UKC Technosolution",
        595 to "Xicato Inc.",
        596 to "Playbrush",
        597 to "Dai Nippon Printing Co., Ltd.",
        598 to "G24 Power Limited",
        599 to "AdBabble Local Commerce Inc.",
        600 to "Devialet SA",
        601 to "ALTYOR",
        602 to "University of Applied Sciences Valais/Haute Ecole Valaisanne",
        603 to "Five Interactive, LLC dba Zendo",
        604 to "NetEase（Hangzhou）Network co.Ltd.",
        605 to "Lexmark International Inc.",
        606 to "Fluke Corporation",
        607 to "Yardarm Technologies",
        608 to "SensaRx",
        609 to "SECVRE GmbH",
        610 to "Glacial Ridge Technologies",
        611 to "Identiv, Inc.",
        612 to "DDS, Inc.",
        613 to "SMK Corporation",
        614 to "Schawbel Technologies LLC",
        615 to "XMI Systems SA",
        616 to "Cerevo",
        617 to "Torrox GmbH & Co KG",
        618 to "Gemalto",
        619 to "DEKA Research & Development Corp.",
        620 to "Domster Tadeusz Szydlowski",
        621 to "Technogym SPA",
        622 to "FLEURBAEY BVBA",
        623 to "Aptcode Solutions",
        624 to "LSI ADL Technology",
        625 to "Animas Corp",
        626 to "Alps Electric Co., Ltd.",
        627 to "OCEASOFT",
        628 to "Motsai Research",
        629 to "Geotab",
        630 to "E.G.O. Elektro-Geraetebau GmbH",
        631 to "bewhere inc",
        632 to "Johnson Outdoors Inc",
        633 to "steute Schaltgerate GmbH & Co. KG",
        634 to "Ekomini inc.",
        635 to "DEFA AS",
        636 to "Aseptika Ltd",
        637 to "HUAWEI Technologies Co., Ltd.",
        638 to "HabitAware, LLC",
        639 to "ruwido austria gmbh",
        640 to "ITEC corporation",
        641 to "StoneL",
        642 to "Sonova AG",
        643 to "Maven Machines, Inc.",
        644 to "Synapse Electronics",
        645 to "Standard Innovation Inc.",
        646 to "RF Code, Inc.",
        647 to "Wally Ventures S.L.",
        648 to "Willowbank Electronics Ltd",
        649 to "SK Telecom",
        650 to "Jetro AS",
        651 to "Code Gears LTD",
        652 to "NANOLINK APS",
        653 to "IF, LLC",
        654 to "RF Digital Corp",
        655 to "Church & Dwight Co., Inc",
        656 to "Multibit Oy",
        657 to "CliniCloud Inc",
        658 to "SwiftSensors",
        659 to "Blue Bite",
        660 to "ELIAS GmbH",
        661 to "Sivantos GmbH",
        662 to "Petzl",
        663 to "storm power ltd",
        664 to "EISST Ltd",
        665 to "Inexess Technology Simma KG",
        666 to "Currant, Inc.",
        667 to "C2 Development, Inc.",
        668 to "Blue Sky Scientific, LLC",
        669 to "ALOTTAZS LABS, LLC",
        670 to "Kupson spol. s r.o.",
        671 to "Areus Engineering GmbH",
        672 to "Impossible Camera GmbH",
        673 to "InventureTrack Systems",
        674 to "LockedUp",
        675 to "Itude",
        676 to "Pacific Lock Company",
        677 to "Tendyron Corporation ( 天地融科技股份有限公司 )",
        678 to "Robert Bosch GmbH",
        679 to "Illuxtron international B.V.",
        680 to "miSport Ltd.",
        681 to "Chargelib",
        682 to "Doppler Lab",
        683 to "BBPOS Limited",
        684 to "RTB Elektronik GmbH & Co. KG",
        685 to "Rx Networks, Inc.",
        686 to "WeatherFlow, Inc.",
        687 to "Technicolor USA Inc.",
        688 to "Bestechnic(Shanghai),Ltd",
        689 to "Raden Inc",
        690 to "JouZen Oy",
        691 to "CLABER S.P.A.",
        692 to "Hyginex, Inc.",
        693 to "HANSHIN ELECTRIC RAILWAY CO.,LTD.",
        694 to "Schneider Electric",
        695 to "Oort Technologies LLC",
        696 to "Chrono Therapeutics",
        697 to "Rinnai Corporation",
        698 to "Swissprime Technologies AG",
        699 to "Koha.,Co.Ltd",
        700 to "Genevac Ltd",
        701 to "Chemtronics",
        702 to "Seguro Technology Sp. z o.o.",
        703 to "Redbird Flight Simulations",
        704 to "Dash Robotics",
        705 to "LINE Corporation",
        706 to "Guillemot Corporation",
        707 to "Techtronic Power Tools Technology Limited",
        708 to "Wilson Sporting Goods",
        709 to "Lenovo (Singapore) Pte Ltd. ( 联想（新加坡） )",
        710 to "Ayatan Sensors",
        711 to "Electronics Tomorrow Limited",
        712 to "VASCO Data Security International, Inc.",
        713 to "PayRange Inc.",
        714 to "ABOV Semiconductor",
        715 to "AINA-Wireless Inc.",
        716 to "Eijkelkamp Soil & Water",
        717 to "BMA ergonomics b.v.",
        718 to "Teva Branded Pharmaceutical Products R&D, Inc.",
        719 to "Anima",
        720 to "3M",
        721 to "Empatica Srl",
        722 to "Afero, Inc.",
        723 to "Powercast Corporation",
        724 to "Secuyou ApS",
        725 to "OMRON Corporation",
        726 to "Send Solutions",
        727 to "NIPPON SYSTEMWARE CO.,LTD.",
        728 to "Neosfar",
        729 to "Fliegl Agrartechnik GmbH",
        730 to "Gilvader",
        731 to "Digi International Inc (R)",
        732 to "DeWalch Technologies, Inc.",
        733 to "Flint Rehabilitation Devices, LLC",
        734 to "Samsung SDS Co., Ltd.",
        735 to "Blur Product Development",
        736 to "University of Michigan",
        737 to "Victron Energy BV",
        738 to "NTT docomo",
        739 to "Carmanah Technologies Corp.",
        740 to "Bytestorm Ltd.",
        741 to "Espressif Incorporated ( 乐鑫信息科技(上海)有限公司 )",
        742 to "Unwire",
        743 to "Connected Yard, Inc.",
        744 to "American Music Environments",
        745 to "Sensogram Technologies, Inc.",
        746 to "Fujitsu Limited",
        747 to "Ardic Technology",
        748 to "Delta Systems, Inc",
        749 to "HTC Corporation ",
        750 to "Citizen Holdings Co., Ltd. ",
        751 to "SMART-INNOVATION.inc",
        752 to "Blackrat Software ",
        753 to "The Idea Cave, LLC",
        754 to "GoPro, Inc.",
        755 to "AuthAir, Inc",
        756 to "Vensi, Inc.",
        757 to "Indagem Tech LLC",
        758 to "Intemo Technologies",
        759 to "DreamVisions co., Ltd.",
        760 to "Runteq Oy Ltd",
        761 to "IMAGINATION TECHNOLOGIES LTD ",
        762 to "CoSTAR TEchnologies",
        763 to "Clarius Mobile Health Corp.",
        764 to "Shanghai Frequen Microelectronics Co., Ltd.",
        765 to "Uwanna, Inc.",
        766 to "Lierda Science & Technology Group Co., Ltd.",
        767 to "Silicon Laboratories",
        768 to "World Moto Inc.",
        769 to "Giatec Scientific Inc.",
        770 to "Loop Devices, Inc",
        771 to "IACA electronique",
        772 to "Proxy Technologies, Inc.",
        773 to "Swipp ApS",
        774 to "Life Laboratory Inc. ",
        775 to "FUJI INDUSTRIAL CO.,LTD.",
        776 to "Surefire, LLC",
        777 to "Dolby Labs",
        778 to "Ellisys",
        779 to "Magnitude Lighting Converters",
        780 to "Hilti AG",
        781 to "Devdata S.r.l.",
        782 to "Deviceworx",
        783 to "Shortcut Labs",
        784 to "SGL Italia S.r.l.",
        785 to "PEEQ DATA",
        786 to "Ducere Technologies Pvt Ltd ",
        787 to "DiveNav, Inc. ",
        788 to "RIIG AI Sp. z o.o.",
        789 to "Thermo Fisher Scientific ",
        790 to "AG Measurematics Pvt. Ltd. ",
        791 to "CHUO Electronics CO., LTD. ",
        792 to "Aspenta International ",
        793 to "Eugster Frismag AG ",
        794 to "Amber wireless GmbH ",
        795 to "HQ Inc ",
        796 to "Lab Sensor Solutions ",
        797 to "Enterlab ApS ",
        798 to "Eyefi, Inc.",
        799 to "MetaSystem S.p.A. ",
        800 to "SONO ELECTRONICS. CO., LTD ",
        801 to "Jewelbots ",
        802 to "Compumedics Limited ",
        803 to "Rotor Bike Components ",
        804 to "Astro, Inc. ",
        805 to "Amotus Solutions ",
        806 to "Healthwear Technologies (Changzhou)Ltd ",
        807 to "Essex Electronics ",
        808 to "Grundfos A/S",
        809 to "Eargo, Inc. ",
        810 to "Electronic Design Lab ",
        811 to "ESYLUX ",
        812 to "NIPPON SMT.CO.,Ltd",
        813 to "BM innovations GmbH ",
        814 to "indoormap",
        815 to "OttoQ Inc ",
        816 to "North Pole Engineering ",
        817 to "3flares Technologies Inc.",
        818 to "Electrocompaniet A.S. ",
        819 to "Mul-T-Lock",
        820 to "Corentium AS ",
        821 to "Enlighted Inc",
        822 to "GISTIC",
        823 to "AJP2 Holdings, LLC",
        824 to "COBI GmbH ",
        825 to "Blue Sky Scientific, LLC ",
        826 to "Appception, Inc.",
        827 to "Courtney Thorne Limited ",
        828 to "Virtuosys",
        829 to "TPV Technology Limited ",
        830 to "Monitra SA",
        831 to "Automation Components, Inc. ",
        832 to "Letsense s.r.l. ",
        833 to "Etesian Technologies LLC ",
        834 to "GERTEC BRASIL LTDA. ",
        835 to "Drekker Development Pty. Ltd.",
        836 to "Whirl Inc ",
        837 to "Locus Positioning ",
        838 to "Acuity Brands Lighting, Inc ",
        839 to "Prevent Biometrics ",
        840 to "Arioneo",
        841 to "VersaMe ",
        842 to "Vaddio ",
        843 to "Libratone A/S ",
        844 to "HM Electronics, Inc. ",
        845 to "TASER International, Inc.",
        846 to "SafeTrust Inc. ",
        847 to "Heartland Payment Systems ",
        848 to "Bitstrata Systems Inc. ",
        849 to "Pieps GmbH ",
        850 to "iRiding(Xiamen)Technology Co.,Ltd.",
        851 to "Alpha Audiotronics, Inc. ",
        852 to "TOPPAN FORMS CO.,LTD. ",
        853 to "Sigma Designs, Inc. ",
        854 to "Spectrum Brands, Inc. ",
        855 to "Polymap Wireless ",
        856 to "MagniWare Ltd.",
        857 to "Novotec Medical GmbH ",
        858 to "Medicom Innovation Partner a/s ",
        859 to "Matrix Inc. ",
        860 to "Eaton Corporation ",
        861 to "KYS",
        862 to "Naya Health, Inc. ",
        863 to "Acromag ",
        864 to "Insulet Corporation ",
        865 to "Wellinks Inc. ",
        866 to "ON Semiconductor",
        867 to "FREELAP SA ",
        868 to "Favero Electronics Srl ",
        869 to "BioMech Sensor LLC ",
        870 to "BOLTT Sports technologies Private limited",
        871 to "Saphe International ",
        872 to "Metormote AB ",
        873 to "littleBits ",
        874 to "SetPoint Medical ",
        875 to "BRControls Products BV ",
        876 to "Zipcar ",
        877 to "AirBolt Pty Ltd ",
        878 to "KeepTruckin Inc ",
        879 to "Motiv, Inc. ",
        880 to "Wazombi Labs OÜ ",
        881 to "ORBCOMM",
        882 to "Nixie Labs, Inc.",
        883 to "AppNearMe Ltd",
        884 to "Holman Industries",
        885 to "Expain AS",
        886 to "Electronic Temperature Instruments Ltd",
        887 to "Plejd AB",
        888 to "Propeller Health",
        889 to "Shenzhen iMCO Electronic Technology Co.,Ltd",
        890 to "Algoria",
        891 to "Apption Labs Inc.",
        892 to "Cronologics Corporation",
        893 to "MICRODIA Ltd.",
        894 to "lulabytes S.L.",
        895 to "Société des Produits Nestlé S.A. (formerly Nestec S.A.)",
        896 to "LLC MEGA-F service",
        897 to "Sharp Corporation",
        898 to "Precision Outcomes Ltd",
        899 to "Kronos Incorporated",
        900 to "OCOSMOS Co., Ltd.",
        901 to "Embedded Electronic Solutions Ltd. dba e2Solutions",
        902 to "Aterica Inc.",
        903 to "BluStor PMC, Inc.",
        904 to "Kapsch TrafficCom AB",
        905 to "ActiveBlu Corporation",
        906 to "Kohler Mira Limited",
        907 to "Noke",
        908 to "Appion Inc.",
        909 to "Resmed Ltd",
        910 to "Crownstone B.V.",
        911 to "Xiaomi Inc.",
        912 to "INFOTECH s.r.o.",
        913 to "Thingsquare AB",
        914 to "T&D",
        915 to "LAVAZZA S.p.A.",
        916 to "Netclearance Systems, Inc.",
        917 to "SDATAWAY",
        918 to "BLOKS GmbH",
        919 to "LEGO System A/S",
        920 to "Thetatronics Ltd",
        921 to "Nikon Corporation",
        922 to "NeST",
        923 to "South Silicon Valley Microelectronics",
        924 to "ALE International",
        925 to "CareView Communications, Inc.",
        926 to "SchoolBoard Limited",
        927 to "Molex Corporation",
        928 to "IVT Wireless Limited",
        929 to "Alpine Labs LLC",
        930 to "Candura Instruments",
        931 to "SmartMovt Technology Co., Ltd",
        932 to "Token Zero Ltd",
        933 to "ACE CAD Enterprise Co., Ltd. (ACECAD)",
        934 to "Medela, Inc",
        935 to "AeroScout",
        936 to "Esrille Inc.",
        937 to "THINKERLY SRL",
        938 to "Exon Sp. z o.o.",
        939 to "Meizu Technology Co., Ltd.",
        940 to "Smablo LTD",
        941 to "XiQ",
        942 to "Allswell Inc.",
        943 to "Comm-N-Sense Corp DBA Verigo",
        944 to "VIBRADORM GmbH",
        945 to "Otodata Wireless Network Inc.",
        946 to "Propagation Systems Limited",
        947 to "Midwest Instruments & Controls",
        948 to "Alpha Nodus, inc.",
        949 to "petPOMM, Inc",
        950 to "Mattel",
        951 to "Airbly Inc.",
        952 to "A-Safe Limited",
        953 to "FREDERIQUE CONSTANT SA",
        954 to "Maxscend Microelectronics Company Limited",
        955 to "Abbott",
        956 to "ASB Bank Ltd",
        957 to "amadas",
        958 to "Applied Science, Inc.",
        959 to "iLumi Solutions Inc.",
        960 to "Arch Systems Inc.",
        961 to "Ember Technologies, Inc.",
        962 to "Snapchat Inc",
        963 to "Casambi Technologies Oy",
        964 to "Pico Technology Inc.",
        965 to "St. Jude Medical, Inc.",
        966 to "Intricon",
        967 to "Structural Health Systems, Inc.",
        968 to "Avvel International",
        969 to "Gallagher Group",
        970 to "In2things Automation Pvt. Ltd.",
        971 to "SYSDEV Srl",
        972 to "Vonkil Technologies Ltd",
        973 to "Wynd Technologies, Inc.",
        974 to "CONTRINEX S.A.",
        975 to "MIRA, Inc.",
        976 to "Watteam Ltd",
        977 to "Density Inc.",
        978 to "IOT Pot India Private Limited",
        979 to "Sigma Connectivity AB",
        980 to "PEG PEREGO SPA",
        981 to "Wyzelink Systems Inc.",
        982 to "Yota Devices LTD",
        983 to "FINSECUR",
        984 to "Zen-Me Labs Ltd",
        985 to "3IWare Co., Ltd.",
        986 to "EnOcean GmbH",
        987 to "Instabeat, Inc",
        988 to "Nima Labs",
        989 to "Andreas Stihl AG & Co. KG",
        990 to "Nathan Rhoades LLC",
        991 to "Grob Technologies, LLC",
        992 to "Actions (Zhuhai) Technology Co., Limited",
        993 to "SPD Development Company Ltd",
        994 to "Sensoan Oy",
        995 to "Qualcomm Life Inc",
        996 to "Chip-ing AG",
        997 to "ffly4u",
        998 to "IoT Instruments Oy",
        999 to "TRUE Fitness Technology",
    )
}
