package com.steleot.blekotlin.internal.utils

import android.bluetooth.BluetoothAdapter
import android.bluetooth.BluetoothDevice
import android.bluetooth.BluetoothGatt
import android.bluetooth.le.ScanCallback

internal val bluetoothStatuses by lazy {
    mapOf(
        BluetoothAdapter.STATE_OFF to "Bluetooth state off",
        BluetoothAdapter.STATE_TURNING_ON to "Bluetooth state turning on",
        BluetoothAdapter.STATE_ON to "Bluetooth state on",
        BluetoothAdapter.STATE_TURNING_OFF to "Bluetooth state turning off",
    )
}

internal val bluetoothBondStates by lazy {
    mapOf(
        BluetoothDevice.BOND_NONE to "Bond none",
        BluetoothDevice.BOND_BONDING to "Bond bonding",
        BluetoothDevice.BOND_BONDED to "Bond bonded",
    )
}

internal val scanCallbackStatuses by lazy {
    mapOf(
        ScanCallback.SCAN_FAILED_ALREADY_STARTED to "Ble scan failed - Already started",
        ScanCallback.SCAN_FAILED_APPLICATION_REGISTRATION_FAILED to "Ble scan failed - Application registration failed",
        ScanCallback.SCAN_FAILED_INTERNAL_ERROR to "Ble scan failed - Internal server error",
        ScanCallback.SCAN_FAILED_FEATURE_UNSUPPORTED to "Ble scan failed - Feature unsupported",
    )
}

internal val gattStatuses by lazy {
    mapOf(
        BluetoothGatt.GATT_SUCCESS to "Gatt success",
        0x01 to "Gatt invalid handle",
        BluetoothGatt.GATT_READ_NOT_PERMITTED to "Gatt read not permitted",
        BluetoothGatt.GATT_WRITE_NOT_PERMITTED to "Gatt write not permitted",
        0x04 to "Gatt invalid pdu",
        BluetoothGatt.GATT_INSUFFICIENT_AUTHENTICATION to "Gatt insufficient authentication",
        BluetoothGatt.GATT_REQUEST_NOT_SUPPORTED to "Gatt request not supported",
        BluetoothGatt.GATT_INVALID_OFFSET to "Gatt invalid offset",
        0x08 to "Gatt insufficient authorization or connection timeout",
        0x09 to "Gatt prepare q full",
        0x0a to "Gatt not found",
        0x0b to "Gatt not long",
        0x0c to "Gatt insufficient key size",
        BluetoothGatt.GATT_INVALID_ATTRIBUTE_LENGTH to "Gatt invalid attribute length",
        0x0e to "Gatt error unlikely",
        BluetoothGatt.GATT_INSUFFICIENT_ENCRYPTION to "Gatt insufficient encryption",
        0x10 to "Gatt unsupported grp type",
        0x11 to "Gatt insufficient resource",
        0x13 to "Gatt connection terminate peer user",
        0x16 to "Gatt connection terminate local host",
        0x22 to "Gatt connection lmp timeout",
        0x3e to "Gatt connection fail establish",
        0x87 to "GATT_ILLEGAL_PARAMETER",
        0x80 to "Gatt no resources",
        0x81 to "Gatt internal error",
        0x82 to "Gatt wrong state",
        0x83 to "Gatt db full",
        0x84 to "Gatt busy",
        0x85 to "Gatt error",
        0x86 to "Gatt cmd started",
        0x88 to "Gatt pending",
        0x89 to "Gatt auth fail",
        0x8a to "Gatt more",
        0x8b to "Gatt invalid cfg",
        0x8c to "Gatt service started",
        0x8d to "Gatt encrypted no mitm",
        0x8e to "Gatt not encrypted",
        BluetoothGatt.GATT_CONNECTION_CONGESTED to "Gatt connection congested",
        0xfd to "Gatt ccc cfg err",
        0xfe to "Gatt prc in progress",
        0xff to "Gatt out of range",
        0x100 to "Gatt connection cancel",
        BluetoothGatt.GATT_FAILURE to "Gatt failure"
    )
}

internal val gattServicesUuids by lazy {
    mapOf(
        "1811" to "Alert Notification Service",
        "180F" to "Battery Service",
        "1810" to "Blood Pressure",
        "181B" to "Body Composition",
        "181E" to "Bond Management",
        "181F" to "Continuous Glucose Monitoring",
        "1805" to "Current Time Service",
        "1818" to "Cycling Power",
        "1816" to "Cycling Speed and Cadence",
        "180A" to "Device Information",
        "181A" to "Environmental Sensing",
        "1800" to "Generic Access",
        "1801" to "Generic Attribute",
        "1808" to "Glucose",
        "1809" to "Health Thermometer",
        "180D" to "Heart Rate",
        "1812" to "Human Interface Device",
        "1802" to "Immediate Alert",
        "1803" to "Link Loss",
        "1819" to "Location and Navigation",
        "1820" to "Internet Protocol Support",
        "1807" to "Next DST Change Service",
        "180E" to "Phone Alert Status Service",
        "1806" to "Reference Time Update Service",
        "1814" to "Running Speed and Cadence",
        "1813" to "Scan Parameters",
        "1804" to "Tx Power",
        "181C" to "User Data",
        "181D" to "Weight Scale",
        "1815" to "Automation IO",
        "1802" to "Immediate Alert Service 1.1",
        "1803" to "Link Loss Service 1.1",
        "1804" to "Tx Power Service 1.1",
    )
}

internal val gattCharacteristicUuids by lazy {
    mapOf(
        "2A7E" to "Aerobic Heart Rate Lower Limit",
        "2A84" to "Aerobic Heart Rate Upper Limit",
        "2A7F" to "Aerobic Threshold",
        "2A80" to "Age",
        "2A43" to "Alert Category ID",
        "2A42" to "Alert Category ID Bit Mask",
        "2A06" to "Alert Level",
        "2A44" to "Alert Notification Control Point",
        "2A3F" to "Alert Status",
        "2A81" to "Anaerobic Heart Rate Lower Limit",
        "2A82" to "Anaerobic Heart Rate Upper Limit",
        "2A83" to "Anaerobic Threshold",
        "2A73" to "Apparent Wind Direction",
        "2A72" to "Apparent Wind Speed",
        "2A01" to "Appearance",
        "2AA3" to "Barometric Pressure Trend",
        "2A19" to "Battery Level",
        "2A49" to "Blood Pressure Feature",
        "2A35" to "Blood Pressure Measurement",
        "2A9B" to "Body Composition Feature",
        "2A9C" to "Body Composition Measurement",
        "2A38" to "Body Sensor Location",
        "2AA4" to "Bond Management Control Point",
        "2AA5" to "Bond Management Feature",
        "2A22" to "Boot Keyboard Input Report",
        "2A32" to "Boot Keyboard Output Report",
        "2A33" to "Boot Mouse Input Report",
        "2AA6" to "Central Address Resolution",
        "2AA8" to "CGM Feature",
        "2AA7" to "CGM Measurement",
        "2AAB" to "CGM Session Run Time",
        "2AAA" to "CGM Session Start Time",
        "2AAC" to "CGM Specific Ops Control Point",
        "2AA9" to "CGM Status",
        "2A5C" to "CSC Feature",
        "2A5B" to "CSC Measurement",
        "2A2B" to "Current Time",
        "2A66" to "Cycling Power Control Point",
        "2A65" to "Cycling Power Feature",
        "2A63" to "Cycling Power Measurement",
        "2A64" to "Cycling Power Vector",
        "2A99" to "Database Change Increment",
        "2A85" to "Date of Birth",
        "2A86" to "Date of Threshold Assessment ",
        "2A08" to "Date Time",
        "2A0A" to "Day Date Time",
        "2A09" to "Day of Week",
        "2A7D" to "Descriptor Value Changed",
        "2A00" to "Device Name",
        "2A7B" to "Dew Point",
        "2A0D" to "DST Offset",
        "2A6C" to "Elevation",
        "2A87" to "Email Address",
        "2A0C" to "Exact Time 256",
        "2A88" to "Fat Burn Heart Rate Lower Limit",
        "2A89" to "Fat Burn Heart Rate Upper Limit",
        "2A26" to "Firmware Revision String",
        "2A8A" to "First Name",
        "2A8B" to "Five Zone Heart Rate Limits",
        "2A8C" to "Gender",
        "2A51" to "Glucose Feature",
        "2A18" to "Glucose Measurement",
        "2A34" to "Glucose Measurement Context",
        "2A74" to "Gust Factor",
        "2A27" to "Hardware Revision String",
        "2A39" to "Heart Rate Control Point",
        "2A8D" to "Heart Rate Max",
        "2A37" to "Heart Rate Measurement",
        "2A7A" to "Heat Index",
        "2A8E" to "Height",
        "2A4C" to "HID Control Point",
        "2A4A" to "HID Information",
        "2A8F" to "Hip Circumference",
        "2A6F" to "Humidity",
        "2A2A" to "IEEE 11073-20601 Regulatory Certification Data List",
        "2A36" to "Intermediate Cuff Pressure",
        "2A1E" to "Intermediate Temperature",
        "2A77" to "Irradiance",
        "2AA2" to "Language",
        "2A90" to "Last Name",
        "2A6B" to "LN Control Point",
        "2A6A" to "LN Feature",
        "2A0F" to "Local Time Information",
        "2A67" to "Location and Speed",
        "2A2C" to "Magnetic Declination",
        "2AA0" to "Magnetic Flux Density - 2D",
        "2AA1" to "Magnetic Flux Density - 3D",
        "2A29" to "Manufacturer Name String",
        "2A91" to "Maximum Recommended Heart Rate",
        "2A21" to "Measurement Interval",
        "2A24" to "Model Number String",
        "2A68" to "Navigation",
        "2A46" to "New Alert",
        "2A04" to "Peripheral Preferred Connection Parameters",
        "2A02" to "Peripheral Privacy Flag",
        "2A50" to "PnP ID",
        "2A75" to "Pollen Concentration",
        "2A69" to "Position Quality",
        "2A6D" to "Pressure",
        "2A4E" to "Protocol Mode",
        "2A78" to "Rainfall",
        "2A03" to "Reconnection Address",
        "2A52" to "Record Access Control Point",
        "2A14" to "Reference Time Information",
        "2A4D" to "Report",
        "2A4B" to "Report Map",
        "2A92" to "Resting Heart Rate",
        "2A40" to "Ringer Control Point",
        "2A41" to "Ringer Setting",
        "2A54" to "RSC Feature",
        "2A53" to "RSC Measurement",
        "2A55" to "SC Control Point",
        "2A4F" to "Scan Interval Window",
        "2A31" to "Scan Refresh",
        "2A5D" to "Sensor Location",
        "2A25" to "Serial Number String",
        "2A05" to "Service Changed",
        "2A28" to "Software Revision String",
        "2A93" to "Sport Type for Aerobic and Anaerobic Thresholds",
        "2A47" to "Supported New Alert Category",
        "2A48" to "Supported Unread Alert Category",
        "2A23" to "System ID",
        "2A6E" to "Temperature",
        "2A1C" to "Temperature Measurement",
        "2A1D" to "Temperature Type",
        "2A94" to "Three Zone Heart Rate Limits",
        "2A12" to "Time Accuracy",
        "2A13" to "Time Source",
        "2A16" to "Time Update Control Point",
        "2A17" to "Time Update State",
        "2A11" to "Time with DST",
        "2A0E" to "Time Zone",
        "2A71" to "True Wind Direction",
        "2A70" to "True Wind Speed",
        "2A95" to "Two Zone Heart Rate Limit",
        "2A07" to "Tx Power Level",
        "2A45" to "Unread Alert Status",
        "2A9F" to "User Control Point",
        "2A9A" to "User Index",
        "2A76" to "UV Index",
        "2A96" to "VO2 Max",
        "2A97" to "Waist Circumference",
        "2A98" to "Weight",
        "2A9D" to "Weight Measurement",
        "2A9E" to "Weight Scale Feature",
        "2A79" to "Wind Chill",
        "2A5A" to "Aggregate",
        "2AB3" to "Altitude",
        "2A58" to "Analog",
        "2A56" to "Digital",
    )
}

internal val gattDescriptorUuids by lazy {
    mapOf(
        "2900" to "Characteristic Extended Properties",
        "2901" to "Characteristic User Description",
        "2902" to "Client Characteristic Configuration",
        "2903" to "Server Characteristic Configuration",
        "2904" to "Characteristic Presentation Format",
        "2905" to "Characteristic Aggregate Format",
        "2906" to "Valid Range",
        "2907" to "External Report Reference",
        "2908" to "Report Reference",
        "290B" to "Environmental Sensing Configuration",
        "290C" to "Environmental Sensing Measurement",
        "290D" to "Environmental Sensing Trigger Setting",
        "2909" to "Number of Digitals",
        "290A" to "Value Trigger Setting",
        "290E" to "Time Trigger Setting",
    )
}
