package com.steleot.blekotlin.constants

/**
 * The available uuids as Strings for the gatt characteristics. This list will updated constantly.
 * Based on [link](https://btprodspecificationrefs.blob.core.windows.net/assigned-values/16-bit%20UUID%20Numbers%20Document.pdf)
 */
object BleGattServiceUuids {

    const val GENERIC_ACCESS = "1800"
    const val GENERIC_ATTRIBUTE = "1801"
    const val IMMEDIATE_ALERT = "1802"
    const val LINK_LOSS = "1803"
    const val TX_POWER = "1804"
    const val CURRENT_TIME_SERVICE = "1805"
    const val REFERENCE_TIME_UPDATE_SERVICE = "1806"
    const val NEXT_DST_CHANGE_SERVICE = "1807"
    const val GLUCOSE = "1808"
    const val HEALTH_THERMOMETER = "1809"
    const val DEVICE_INFORMATION = "180A"
    const val HEART_RATE = "180D"
    const val PHONE_ALERT_STATUS_SERVICE = "180E"
    const val BATTERY_SERVICE = "180F"
    const val BLOOD_PRESSURE = "1810"
    const val ALERT_NOTIFICATION_SERVICE = "1811"
    const val HUMAN_INTERFACE_DEVICE = "1812"
    const val SCAN_PARAMETERS = "1813"
    const val RUNNING_SPEED_AND_CADENCE = "1814"
    const val AUTOMATION_IO = "1815"
    const val CYCLING_SPEED_AND_CADENCE = "1816"
    const val CYCLING_POWER = "1818"
    const val LOCATION_AND_NAVIGATION = "1819"
    const val ENVIRONMENTAL_SENSING = "181A"
    const val BODY_COMPOSITION = "181B"
    const val USER_DATA = "181C"
    const val WEIGHT_SCALE = "181D"
    const val BOND_MANAGEMENT = "181E"
    const val CONTINUOUS_GLUCOSE_MONITORING = "181F"
    const val INTERNET_PROTOCOL_SUPPORT = "1820"
    const val INDOOR_PROTOCOL_SUPPORT = "1821"
    const val PULSE_OXIMETER = "1822"
    const val HTTP_PROXY = "1823"
    const val TRANSPORT_DISCOVERY = "1824"
    const val OBJECT_TRANSFER = "1825"
    const val FITNESS_MACHINE = "1826"
    const val MESH_PROVISIONING = "1827"
    const val MESH_PROXY = "1828"
    const val RECONNECTION_CONFIGURATION = "1829"
    const val INSULIN_DELIVERY = "183A"
    const val BINARY_SENSOR = "183B"
    const val EMERGENCY_CONFIGURATION = "183C"
    const val PHYSICAL_ACTIVITY_MONITOR = "183E"
    const val AUDIO_INPUT_CONTROL = "1843"
    const val VOLUME_CONTROL = "1844"
    const val VOLUME_OFFSET_CONTROL = "1845"
    const val DEVICE_TIME = "1847"
}